INSERT INTO menu_items (name, price, description, display_image, ingredients, popular, category, active) VALUES ('Chetnas Poutine', 10, 'Some would argue this is the best poutine in the world', 'https://cn-geo1.uber.com/image-proc/resize/eats/format=webp/width=550/height=440/quality=70/srcb64=aHR0cHM6Ly9kMXJhbHNvZ25qbmczNy5jbG91ZGZyb250Lm5ldC82YzZmZjUwNC1lZDA0LTRjMzEtYjMzOC0xMWM5Y2UxN2JjNDQuanBlZw==', 'cheese curds, fries, gravy', false, 'meat', true);
INSERT INTO menu_items (name, price, description, display_image, ingredients, popular, category, active) VALUES ('Francis Ultimate Sandwich', 15, 'just a sandwhich', 'https://cn-geo1.uber.com/image-proc/resize/eats/format=webp/width=550/height=440/quality=70/srcb64=aHR0cHM6Ly9kMXJhbHNvZ25qbmczNy5jbG91ZGZyb250Lm5ldC9jMTNhNjhkOS1mNzIxLTQ5YTItOTdjOS1kYjJkNDY2N2NhMWMuanBlZw==', 'bread, ham', false, 'sandwich', true);
INSERT INTO menu_items (name, price, description, display_image, ingredients, popular, category, active) VALUES ('Andys Meteor Pizza', 12, 'Has been reported to temporarily provide God-like powers', 'https://cn-geo1.uber.com/image-proc/resize/eats/format=webp/width=550/height=440/quality=70/srcb64=aHR0cHM6Ly9kMXJhbHNvZ25qbmczNy5jbG91ZGZyb250Lm5ldC81MDU0ODYzMC01MzhmLTQ2YzMtYWZlOS0zNTQ3MDI3Njg0NDUucG5n', 'pizza dough, bacon, sour cream, onion, lemons', false, 'pizza', true);
INSERT INTO menu_items (name, price, description, display_image, ingredients, popular, category, active) VALUES ('Vassilys veggie pizza', 11, 'Our staple choice for our vegetarian guests', 'https://cn-geo1.uber.com/image-proc/resize/eats/format=webp/width=550/height=440/quality=70/srcb64=aHR0cHM6Ly9kMXJhbHNvZ25qbmczNy5jbG91ZGZyb250Lm5ldC8yMDAyNzRmYi05ZDc3LTQ5YmUtODVjMi1kNzQ0NzgyNTg0YzYucG5n', 'pizza dough, marinara sauce, spinach, mozzarella cheese, artichoke', false, 'pizza', true);
INSERT INTO menu_items (name, price, description, display_image, ingredients, popular, category, active) VALUES ('Doms Doughnuts', 7, 'Assorted Array of doughtnuts, pun included', 'https://cn-geo1.uber.com/image-proc/resize/eats/format=webp/width=550/height=440/quality=70/srcb64=aHR0cHM6Ly9kMXJhbHNvZ25qbmczNy5jbG91ZGZyb250Lm5ldC8xMGM1YjMzMC1iM2M3LTQ4YmUtYWE0My04NGM1Zjk0MmI3MDMuanBlZw==', 'ingredients may differ day by day', false, 'dessert', true);
INSERT INTO menu_items (name, price, description, display_image, ingredients, popular, category, active) VALUES ('Grigors Greek Salad', 8, 'Healthy choice to energize you after a long coding session', 'https://cn-geo1.uber.com/image-proc/resize/eats/format=webp/width=550/height=440/quality=70/srcb64=aHR0cHM6Ly9kMXJhbHNvZ25qbmczNy5jbG91ZGZyb250Lm5ldC8yZjdkYzQ4OS03YTVhLTQ2YWUtYWE5Mi0xNmU4ZmU3YWU2YWEuanBlZw==', 'onion, tomatoes, olives, cucumbers, feta cheese', false, 'Entree', true);
INSERT INTO menu_items (name, price, description, display_image, ingredients, popular, category, active) VALUES ('Tylers Rib Steak', 14, '16 oz Rib steak, dry-aged for 3 weeks', 'https://cn-geo1.uber.com/image-proc/resize/eats/format=webp/width=550/height=440/quality=70/srcb64=aHR0cHM6Ly9kMXJhbHNvZ25qbmczNy5jbG91ZGZyb250Lm5ldC81NzQ4NzM1Zi1kMzhiLTQ1YmYtYjFhMy1mNzc4MGQ5NWJjODMuanBlZw==', 'steak, garlic, soy sauce, butter', false, 'meat', true);
INSERT INTO menu_items (name, price, description, display_image, ingredients, popular, category, active) VALUES ('Mohameds Chicken Burger', 15, 'Alternate sandwich to Francis\ ultimate mega sandwich, but why would you?', 'https://cn-geo1.uber.com/image-proc/resize/eats/format=webp/width=550/height=440/quality=70/srcb64=aHR0cHM6Ly9kMXJhbHNvZ25qbmczNy5jbG91ZGZyb250Lm5ldC80NzkyMGE3MS02N2ZjLTQzOTAtOTg0Yy0zNDAzN2I0Y2Y1YzYuanBlZw==', 'buttermilk, cayenne sauce, boneless chicken breast', false, 'sandwich', true);
INSERT INTO menu_items (name, price, description, display_image, ingredients, popular, category, active) VALUES ('Janelles Jello Fondant', 5, 'The perfect choice of dessert after a meal', 'https://cn-geo1.uber.com/image-proc/resize/eats/format=webp/width=550/height=440/quality=70/srcb64=aHR0cHM6Ly9kMXJhbHNvZ25qbmczNy5jbG91ZGZyb250Lm5ldC9mMjcxMzhkZi0yNmRiLTQ5M2YtOWQ0NS02OWIxMzA2NTdiMzEuanBlZw==', 'gelatin, milk, sugar, cocoa powder', false, 'dessert', true);
INSERT INTO menu_items (name, price, description, display_image, ingredients, popular, category, active) VALUES ('Garys Macaroni Loops', 9, 'We promise this will send you in a loop', 'https://cn-geo1.uber.com/image-proc/resize/eats/format=webp/width=550/height=440/quality=70/srcb64=aHR0cHM6Ly9kMXJhbHNvZ25qbmczNy5jbG91ZGZyb250Lm5ldC9mYjVkNzNmNi0xODAwLTQzODgtOGRkNC1jNDU2NjQ3Y2RhYzAuanBlZw==', 'pasta, tomato paste, meatballs', false, 'pasta', true);


