INSERT INTO menu_items (name, price, description, display_image, ingredients, popular, category, active) VALUES ('Chetna\s poutine', 10, 'Some would argue this is the best poutine in the world', 'https://images.immediate.co.uk/production/volatile/sites/30/2020/08/south-african-chutney-chicken-03a0407.jpg', 'cheese curds, fries, gravy', false, 'meat', true);
INSERT INTO menu_items (name, price, description, display_image, ingredients, popular, category, active) VALUES ('Francis\ ultimate mega sandwich', 15, 'just a sandwhich', 'https://media.gettyimages.com/photos/bologna-sandwich-picture-id88179833?s=170667a', 'bread, ham', false, 'sandwich', true);
INSERT INTO menu_items (name, price, description, display_image, ingredients, popular, category, active) VALUES ('Andy\s anchovy pizza', 12, 'Has been reported to temporarily provide God-like powers', 'https://www.craftbeering.com/wp-content/uploads/2019/03/Anchovies-pizza-SQ-720x720.jpg', 'pizza dough, achovy, sour cream, onion, lemons', false, 'pizza', true);
INSERT INTO menu_items (name, price, description, display_image, ingredients, popular, category, active) VALUES ('Vassily\s veggie pizza', 11, 'Our staple choice for our vegetarian guests', 'https://cookieandkate.com/images/2020/10/best-veggie-pizza-recipe-1.jpg', 'pizza dough, marinara sauce, spinach, mozzarella cheese, artichoke', false, 'pizza', true);
INSERT INTO menu_items (name, price, description, display_image, ingredients, popular, category, active) VALUES ('Dom\s doughnuts', 7, 'Assorted Array of doughtnuts, pun included', 'https://i2.wp.com/completelydelicious.com/wp-content/uploads/2021/02/yeast-raised-doughnuts-6.jpg', 'ingredients may differ day by day', false, 'dessert', true);
INSERT INTO menu_items (name, price, description, display_image, ingredients, popular, category, active) VALUES ('Grigor\s goulash', 8, 'Stew to warm up your weary bones from too much coding', 'https://hips.hearstapps.com/del.h-cdn.co/assets/17/37/1600x2399/gallery-1505333414-goulash-delish.jpg?resize=480:*', 'onion, garlic, ground beef', false, 'Entree', true);
INSERT INTO menu_items (name, price, description, display_image, ingredients, popular, category, active) VALUES ('Tyler\s T-bone steak', 14, '14 oz T-bone steak, dry-aged for 3 weeks', 'https://images.immediate.co.uk/production/volatile/sites/2/2018/10/Pan-Fried-T-Bone-Steak-284bfa5.jpg?quality=90&resize=768%2C574', 'steak, garlic, soy sauce, butter', false, 'meat', true);
INSERT INTO menu_items (name, price, description, display_image, ingredients, popular, category, active) VALUES ('Mohamed\s chicken sandwich', 15, 'Alternate sandwich to Francis\ ultimate mega sandwich, but why would you?', 'https://topsecretrecipes.com/images/product/popeyes-chicken-sandwich-copycat-recipe.jpg', 'buttermilk, cayenne sauce, boneless chicken breast', false, 'sandwich', true);
INSERT INTO menu_items (name, price, description, display_image, ingredients, popular, category, active) VALUES ('Janelle\s jello pudding', 5, 'The perfect choice of dessert after a meal', 'https://www.seriouseats.com/recipes/images/2012/01/20111231jellospoon610.jpg', 'gelatin, milk, sugar, cocoa powder', false, 'dessert', true);
INSERT INTO menu_items (name, price, description, display_image, ingredients, popular, category, active) VALUES ('Gary\s macaroni loops', 9, 'We promise this will send you in a loop', 'https://chocolatecoveredkatie.com/wp-content/uploads/2013/08/homemade-spaghettios-recipe.jpg', 'pasta, tomato paste, meatballs', false, 'pasta', true);


