DROP TABLE IF EXISTS orders CASCADE;
CREATE TABLE orders(
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  item_id INTEGER REFERENCES menu_items(id) ON DELETE CASCADE,
  ordered_at TIMESTAMP,
  order_finished TIMESTAMP,
  order_status BOOLEAN DEFAULT FALSE

);
