DROP TABLE IF EXISTS user_orders CASCADE;
CREATE TABLE user_orders(
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  item_id INTEGER REFERENCES menu_items(id) ON DELETE CASCADE,
  total_price INTEGER DEFAULT 0
);
